# Generated by Django 2.0.5 on 2018-08-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20180814_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='stupid',
            field=models.BooleanField(default=True),
        ),
    ]
